### Q1.Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.                                                                          HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

### solution

In [1]:
import numpy as np


In [9]:
vec=np.array([1,2,3,4,5])
n=5
def func(vec,n,increasing=True):
    if increasing:
        mat=np.matrix([x**i for x in vec for i in range(n)]).reshape(n,n)
    else:
        mat=np.matrix([x**(n-i-1) for x in vec for i in range(n)]).reshape(n,n)
    return mat
print(func(vec,n))

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


In [10]:
print(func(vec,n,False))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


### Q2.Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

### solution

In [22]:
in_ar = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
temp=[]
def movingAverage(in_ar,k):
    n=len(in_ar)
    for i in range(n-k+1):
        temp.append(np.round(((in_ar[i]+in_ar[i+1]+in_ar[i+2])/k),2))
    return temp
movingAverage(in_ar, k)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]