In [1]:
import numpy as np


# solution 1

In [9]:
vec=np.array([1,2,3,4,5])
n=5
def func(vec,n,increasing=True):
    if increasing:
        mat=np.matrix([x**i for x in vec for i in range(n)]).reshape(n,n)
    else:
        mat=np.matrix([x**(n-i-1) for x in vec for i in range(n)]).reshape(n,n)
    return mat
print(func(vec,n))

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


In [10]:
print(func(vec,n,False))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


# solution 2

In [22]:
in_ar = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
temp=[]
def movingAverage(in_ar,k):
    n=len(in_ar)
    for i in range(n-k+1):
        temp.append(np.round(((in_ar[i]+in_ar[i+1]+in_ar[i+2])/k),2))
    return temp
movingAverage(in_ar, k)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]